In [1]:
print ("Hello Zohal")

Hello Zohal

In [4]:
import pandas as pd

In [8]:
import pandas as pd
data = {
    "Name" : [ "Zohal", "Anna", "John"],
    "Age" : [25, 30, 22]

}

df = pd.DataFrame(data)
print(df)

    Name  Age
0  Zohal   25
1   Anna   30
2   John   22

In [9]:
df. head()

    Name  Age
0  Zohal   25
1   Anna   30
2   John   22

In [10]:
df.describe()

             Age
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000

In [13]:
df["Age"]

0    25
1    30
2    22
Name: Age, dtype: int64

In [15]:
df["Age"] .mean()

np.float64(25.666666666666668)

In [16]:
df[df["Age"] > 25]

   Name  Age
1  Anna   30

In [19]:
df["Age_in_5_years"] = df["Age"] + 5 
df

    Name  Age  Age_in_5_years
0  Zohal   25              30
1   Anna   30              35
2   John   22              27

In [21]:
df.sort_values("Age")

    Name  Age  Age_in_5_years
2   John   22              27
0  Zohal   25              30
1   Anna   30              35

In [22]:
df.describe()

             Age  Age_in_5_years
count   3.000000        3.000000
mean   25.666667       30.666667
std     4.041452        4.041452
min    22.000000       27.000000
25%    23.500000       28.500000
50%    25.000000       30.000000
75%    27.500000       32.500000
max    30.000000       35.000000

In [23]:
df[df["Age"] > 25]

   Name  Age  Age_in_5_years
1  Anna   30              35

In [24]:
df.sort_values("Age")

    Name  Age  Age_in_5_years
2   John   22              27
0  Zohal   25              30
1   Anna   30              35

In [26]:
df["Double Age"] = df["Age"] * 2
df

    Name  Age  Age_in_5_years  Double Age
0  Zohal   25              30          50
1   Anna   30              35          60
2   John   22              27          44

In [27]:
df.iloc[0]

Name              Zohal
Age                  25
Age_in_5_years       30
Double Age           50
Name: 0, dtype: object

In [29]:
df[df["Age"] > 25]

   Name  Age  Age_in_5_years  Double Age
1  Anna   30              35          60

In [31]:
df.sort_values("Age")

    Name  Age  Age_in_5_years  Double Age
2   John   22              27          44
0  Zohal   25              30          50
1   Anna   30              35          60

In [34]:
df.sort_values("Age", ascending=False)

    Name  Age  Age_in_5_years  Double Age
1   Anna   30              35          60
0  Zohal   25              30          50
2   John   22              27          44

In [35]:
df[["Name", "Age"]]

    Name  Age
0  Zohal   25
1   Anna   30
2   John   22

In [37]:
len(df)

3

In [38]:
df.sort_values("Age")

    Name  Age  Age_in_5_years  Double Age
2   John   22              27          44
0  Zohal   25              30          50
1   Anna   30              35          60

In [39]:
df.sort_values("Age",ascending=False)

    Name  Age  Age_in_5_years  Double Age
1   Anna   30              35          60
0  Zohal   25              30          50
2   John   22              27          44

In [40]:
df[df["Age"] > 24]

    Name  Age  Age_in_5_years  Double Age
0  Zohal   25              30          50
1   Anna   30              35          60

In [41]:
df["Age_plus_10"]= df["Age"] + 10
df

    Name  Age  Age_in_5_years  Double Age  Age_plus_10
0  Zohal   25              30          50           35
1   Anna   30              35          60           40
2   John   22              27          44           32

In [42]:
df.sort_values("Double Age")

    Name  Age  Age_in_5_years  Double Age  Age_plus_10
2   John   22              27          44           32
0  Zohal   25              30          50           35
1   Anna   30              35          60           40

In [43]:
df[df["Double Age"] > 45]

    Name  Age  Age_in_5_years  Double Age  Age_plus_10
0  Zohal   25              30          50           35
1   Anna   30              35          60           40

In [44]:
df["Name"]

0    Zohal
1     Anna
2     John
Name: Name, dtype: str

In [45]:
df["Age"]

0    25
1    30
2    22
Name: Age, dtype: int64

In [49]:
df[["Name", "Age"]]

    Name  Age
0  Zohal   25
1   Anna   30
2   John   22

In [50]:
df["Age"].mean()

np.float64(25.666666666666668)

In [51]:
df["Age"].max()

np.int64(30)

In [52]:
df["Age"].min()

np.int64(22)

In [53]:
df["Age"].sum()

np.int64(77)

In [55]:
df["Group"] = ["Young","Adult","Young"]
df

    Name  Age  Age_in_5_years  Double Age  Age_plus_10  Group
0  Zohal   25              30          50           35  Young
1   Anna   30              35          60           40  Adult
2   John   22              27          44           32  Young

In [56]:
df.groupby("Group")["Age"].mean()

Group
Adult    30.0
Young    23.5
Name: Age, dtype: float64

In [57]:
df.groupby("Group").sum()

            Name  Age  Age_in_5_years  Double Age  Age_plus_10
Group
Adult       Anna   30              35          60           40
Young  ZohalJohn   47              57          94           67

df.describ()